name: Deploy DotNet project to Azure Function App

on:
  push:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_NAME: 'fn-githubproxy-dev'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'github-util\fn-githubproxy'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  README_PATH: 'azure-sentinel\MSSPVersion\README.md'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: development
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd '.\${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Update README.md
        shell: pwsh
        run: |
          pushd '.\${{ env.README_PATH }}'
          sed -i 's/fn-githubproxy.azurewebsites.net%2Fapi%2Fgithubproxy%3Fcode%3DlLWMaz9g8KcxbALqisKniiDTgEJ1V6efZz6DBUxBD9yyAzFuKTvACg%3D%3D/fn-githubproxy-dev.azurewebsites.net%2Fapi%2Ffn-githubproxy%3Fcode%3D4fYObdW9GVZzT39q6jz1ozi35D1lm3wq1kqtapkPb9t5AzFu_RAf8Q%3D%3D/g' README.md

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples