name: Deploy DotNet project to Azure Function App

on:
  push:
    branches:
      - main
      - qa

env:
  AZURE_FUNCTIONAPP_NAME: 'fn-githubproxy-prod'  # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'github-util\fn-githubproxy'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  README_PATH: 'azure-sentinel\MSSPVersion'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Update README.md
      shell: pwsh
      run: |
        pushd '.\${{ env.README_PATH }}'
        sed -i 's/fn-githubproxy-dev.azurewebsites.net%2Fapi%2Ffn-githubproxy%3Fcode%3D4fYObdW9GVZzT39q6jz1ozi35D1lm3wq1kqtapkPb9t5AzFu_RAf8Q%3D%3D/fn-githubproxy-prod.azurewebsites.net%2Fapi%2Ffn-githubproxy%3Fcode%3DNvzGPLuXcu5NgGFnlTqiBTE1xY7rM-CZo3WgC1ZFeM0zAzFuoQbRKA%3D%3D/g' README.md  
        sed -i 's/develop/main/g' README.md  
        
        git config --global user.name 'Automation'
        git config --global user.email 'automation@users.noreply.github.com'
        git commit -am "Automated commit"
        git push